# Generated by Django 3.0.8 on 2021-03-21 23:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_account_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spayments_in', to='account.Account')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spayments_out', to='account.Account')),
            ],
        ),
    ]
